# Generated by Django 4.2.2 on 2023-06-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(default=None, max_length=128, null=True)),
                ('date_add', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='LinksAllAnchors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anchor_value', models.TextField()),
                ('date_add', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'links_all_anchors',
            },
        ),
        migrations.CreateModel(
            name='LinksAllDomains',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(default=None, max_length=128, null=True)),
                ('date_add', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'links_all_domains',
            },
        ),
        migrations.CreateModel(
            name='LinksAllUrls',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('date_add', models.DateField(default=None, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='looker.linksalldomains')),
            ],
            options={
                'db_table': 'links_all_urls',
            },
        ),
        migrations.CreateModel(
            name='PbnSites',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(default=None, max_length=128, null=True)),
                ('date_create', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'pbn_sites',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(default=None, max_length=64, null=True)),
                ('ip_server', models.CharField(default=None, max_length=15, null=True)),
                ('date_add', models.DateField(default=None, null=True)),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='looker.clients')),
            ],
            options={
                'db_table': 'servers',
            },
        ),
        migrations.CreateModel(
            name='RelationPbnSitesLinksAllDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pbn_sites', models.IntegerField()),
                ('id_links_all_domains', models.IntegerField()),
                ('links_all_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='looker.linksalldomains')),
                ('pbn_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='looker.pbnsites')),
            ],
            options={
                'db_table': 'relation_pbn_sites_links_all_domains',
            },
        ),
        migrations.AddField(
            model_name='pbnsites',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='looker.servers'),
        ),
        migrations.CreateModel(
            name='PbnArticles',
            fields=[
                ('id_row', models.IntegerField(primary_key=True, serialize=False)),
                ('id_article', models.IntegerField()),
                ('date_create', models.DateTimeField(default=None, null=True)),
                ('date_modified', models.DateTimeField(default=None, null=True)),
                ('text_article', models.TextField()),
                ('article_name', models.TextField()),
                ('article_url', models.TextField()),
                ('pbn_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='looker.pbnsites')),
            ],
            options={
                'db_table': 'pbn_articles',
            },
        ),
        migrations.CreateModel(
            name='MoneySites',
            fields=[
                ('id_row', models.IntegerField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(default=None, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='looker.clients')),
                ('domain', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='looker.linksalldomains')),
            ],
            options={
                'db_table': 'money_sites',
            },
        ),
        migrations.CreateModel(
            name='LinksCheckDonorAcceptor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_url_from_donor', models.IntegerField()),
                ('id_url_to_acceptor', models.IntegerField()),
                ('date_check', models.DateField(default=None, null=True)),
                ('acceptor_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptor_links', to='looker.linksallurls')),
                ('anchor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='looker.linksallanchors')),
                ('donor_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_links', to='looker.linksallurls')),
            ],
            options={
                'db_table': 'links_check_donor_acceptor',
            },
        ),
    ]
