# Generated by Django 4.2.2 on 2023-06-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('looker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkscheckdonoracceptor',
            name='id_url_from_donor',
        ),
        migrations.RemoveField(
            model_name='linkscheckdonoracceptor',
            name='id_url_to_acceptor',
        ),
        migrations.RemoveField(
            model_name='relationpbnsiteslinksalldomains',
            name='id_links_all_domains',
        ),
        migrations.RemoveField(
            model_name='relationpbnsiteslinksalldomains',
            name='id_pbn_sites',
        ),
        migrations.AlterField(
            model_name='moneysites',
            name='domain',
            field=models.ForeignKey(db_column='id_domain', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='looker.linksalldomains'),
        ),
    ]
