# Generated by Django 4.2.2 on 2023-07-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('looker', '0002_clientspbnsitesandarticlesnew_urlschecknew'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbnPlans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('money_site_id', models.IntegerField(blank=True, null=True)),
                ('money_site_name', models.CharField(max_length=255)),
                ('pbn_sites', models.IntegerField()),
                ('links', models.IntegerField()),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'pbn_plans',
            },
        )
    ]