# Generated by Django 4.1.3 on 2022-12-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_setting_service_projectservicesetting_job_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectservicesetting',
            unique_together={('project', 'service', 'setting')},
        ),
    ]
