# Generated by Django 4.1.3 on 2022-12-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_service_servicesettings_project_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
