# Generated by Django 4.1.3 on 2022-12-22 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_service_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesettings',
            old_name='accepted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='service',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicesettings',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Запущен'), (2, 'Успешно завершён'), (3, 'Завершился ошибкой')], default=1)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.service')),
            ],
        ),
    ]
