# Generated by Django 4.1.3 on 2022-12-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectservicesetting_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
