# Generated by Django 4.1.3 on 2023-02-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_job_last_result_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='repeats',
            field=models.IntegerField(default=0),
        ),
    ]
