# Generated by Django 4.1.3 on 2023-02-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_job_repeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_repeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
