# Generated by Django 4.1.3 on 2023-02-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_job_last_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delayed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
