# Generated by Django 4.1.3 on 2023-03-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_projectservicesetting_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'File')], null=True),
        ),
    ]
