# Generated by Django 4.2.2 on 2023-06-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_setting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_class',
            field=models.IntegerField(choices=[(1, 'GoogleIndexer'), (2, 'AhrefsAnalysis'), (3, 'LookerStudio')], null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='settings',
            field=models.ManyToManyField(blank=True, to='project.setting'),
        ),
    ]
