# Generated by Django 4.2.2 on 2023-06-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_service_service_class_alter_service_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='site',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
