# Generated by Django 4.2.2 on 2023-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=128, null=True)),
                ('date_add', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinksAllAnchors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_value', models.TextField(blank=True, null=True)),
                ('date_add', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'links_all_anchors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinksAllDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, max_length=128, null=True)),
                ('date_add', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'links_all_domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinksAllUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('date_add', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'links_all_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinksCheckDonorAcceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_check', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'links_check_donor_acceptor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneySites',
            fields=[
                ('id_row', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'money_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PbnArticles',
            fields=[
                ('id_row', models.AutoField(primary_key=True, serialize=False)),
                ('id_article', models.IntegerField()),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('text_article', models.TextField(blank=True, null=True)),
                ('article_name', models.TextField(blank=True, null=True)),
                ('article_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pbn_articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PbnSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(blank=True, max_length=128, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pbn_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationPbnSitesLinksAllDomains',
            fields=[
                ('id_pbn_sites', models.IntegerField(primary_key=True, serialize=False)),
                ('id_links_all_domains', models.IntegerField()),
            ],
            options={
                'db_table': 'relation_pbn_sites_links_all_domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_server', models.CharField(blank=True, max_length=15, null=True)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('date_add', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servers',
                'managed': False,
            },
        ),
    ]
